export const images = [
  {
    position: [0, 0, 1.5],
    rotation: [0, 0, 0],
    url: '/images/unseen.png',
    audioUrl: '/songs/unseen.mov',
    isStill: true,
    name: 'Unseen',
    type: 'Still Image',
  },
  // Back
  {
    position: [-0.8, 0, -0.6],
    rotation: [0, 0, 0],
    url: '/images/seen.png',
    audioUrl: '/songs/seen.mov',
    isStill: true,
    name: 'Seen',
    type: 'Still Image',
  },
  {
    position: [0.8, 0, -0.6],
    rotation: [0, 0, 0],
    url: '/images/unseen.png',
    audioUrl: '/songs/unseen.mov',
    isStill: true,
    name: 'Unseen',
    type: 'Still Image',
  },
  // Left
  {
    position: [-1.75, 0, 0.25],
    rotation: [0, Math.PI / 2.5, 0],
    url: 'https://ezgi-dissertation.s3.us-west-2.amazonaws.com/fragment-self.mp4',
    isVideo: true,
    name: 'Fragmented Self',
    type: 'AI Generated',
  },
  {
    position: [-2.15, 0, 1.5],
    rotation: [0, Math.PI / 2.5, 0],
    url: 'https://ezgi-dissertation.s3.us-west-2.amazonaws.com/cosmic-self.mp4',
    isVideo: true,
    name: 'Cosmic Self',
    type: 'Animation',
  },
  {
    position: [-2, 0, 2.75],
    rotation: [0, Math.PI / 2.5, 0],
    url: 'https://ezgi-dissertation.s3.us-west-2.amazonaws.com/enlightenment.mp4',
    isVideo: true,
    name: 'Enlightenment',
    type: 'GIF',
  },
  // Right
  {
    position: [1.75, 0, 0.25],
    rotation: [0, -Math.PI / 2.5, 0],
    url: 'https://ezgi-dissertation.s3.us-west-2.amazonaws.com/ancestral-self.mov',
    isVideo: true,
    name: 'Ancestral Self',
    type: 'AI Generated',
  },
  {
    position: [2.15, 0, 1.5],
    rotation: [0, -Math.PI / 2.5, 0],
    url: 'https://ezgi-dissertation.s3.us-west-2.amazonaws.com/emotional-self.mp4',
    isVideo: true,
    name: 'Emotional Self',
    type: 'Animation',
  },
  {
    position: [2, 0, 2.75],
    rotation: [0, -Math.PI / 2.5, 0],
    url: 'https://ezgi-dissertation.s3.us-west-2.amazonaws.com/dreamland.mp4',
    isVideo: true,
    name: 'Dreamland',
    type: 'GIF',
  },
]
