export const images = [
  {
    position: [0, 0, 1.5],
    rotation: [0, 0, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  // Back
  {
    position: [-0.8, 0, -0.6],
    rotation: [0, 0, 0],
    url: "/images/seen.png",
    audioUrl: "/songs/seen.mov",
    isStill: true,
    name: "Seen",
    type: "Still Image",
  },
  {
    position: [0.8, 0, -0.6],
    rotation: [0, 0, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  // Left
  {
    position: [-1.75, 0, 0.25],
    rotation: [0, Math.PI / 2.5, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  {
    position: [-2.15, 0, 1.5],
    rotation: [0, Math.PI / 2.5, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  {
    position: [-2, 0, 2.75],
    rotation: [0, Math.PI / 2.5, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  // Right
  {
    position: [1.75, 0, 0.25],
    rotation: [0, -Math.PI / 2.5, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  {
    position: [2.15, 0, 1.5],
    rotation: [0, -Math.PI / 2.5, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
  {
    position: [2, 0, 2.75],
    rotation: [0, -Math.PI / 2.5, 0],
    url: "/images/unseen.png",
    audioUrl: "/songs/unseen.mov",
    isStill: true,
    name: "Unseen",
    type: "Still Image",
  },
];
